// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/api/bundle.ts";
import * as $4 from "./routes/api/clients.ts";
import * as $5 from "./routes/api/eval.ts";
import * as $6 from "./routes/api/messages.ts";
import * as $7 from "./routes/api/post.ts";
import * as $8 from "./routes/client.ts";
import * as $9 from "./routes/index.tsx";
import * as $10 from "./routes/repl.tsx";
import * as $$0 from "./islands/BrowserOnly.tsx";
import * as $$1 from "./islands/Button.tsx";
import * as $$2 from "./islands/Carousel.tsx";
import * as $$3 from "./islands/ClientDropdown.tsx";
import * as $$4 from "./islands/ColoredButton.tsx";
import * as $$5 from "./islands/Editor.tsx";
import * as $$6 from "./islands/Input.tsx";
import * as $$7 from "./islands/REPL.tsx";
import * as $$8 from "./islands/ScriptDropdown.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/api/bundle.ts": $3,
    "./routes/api/clients.ts": $4,
    "./routes/api/eval.ts": $5,
    "./routes/api/messages.ts": $6,
    "./routes/api/post.ts": $7,
    "./routes/client.ts": $8,
    "./routes/index.tsx": $9,
    "./routes/repl.tsx": $10,
  },
  islands: {
    "./islands/BrowserOnly.tsx": $$0,
    "./islands/Button.tsx": $$1,
    "./islands/Carousel.tsx": $$2,
    "./islands/ClientDropdown.tsx": $$3,
    "./islands/ColoredButton.tsx": $$4,
    "./islands/Editor.tsx": $$5,
    "./islands/Input.tsx": $$6,
    "./islands/REPL.tsx": $$7,
    "./islands/ScriptDropdown.tsx": $$8,
  },
  baseUrl: import.meta.url,
};

export default manifest;
