import type { EditorProps, Monaco } from "types/monaco.ts";
import useMount from "hooks/useMount.ts";
import { useRef } from "preact/hooks";
import { memo } from "preact/compat";
import Editor from "islands/Editor.tsx";
import { asset } from "$fresh/runtime.ts";
import type { languages } from "monaco-editor";

// Fetch lib.deno.d.ts from from the url generated by asset("lib.deno.d.ts")
// Once fetched, create a new Editor component, and before it is mounted,
// add the extraLibs to the languageDefaults.typescript.extraLibs

const DenoEditor = (props: EditorProps) => {
  const lib = useRef<string>("");
  const monacoRef = useRef<Monaco>();

  const handleBeforeMount = (monaco: Monaco) => {
    monacoRef.current = monaco;
    if (lib.current) loadLib();
    return props.beforeMount?.(monaco);
  };

  const loadLib = () => {
    if (!monacoRef.current || !lib.current) return;

    const compilerOptions: languages.typescript.CompilerOptions = {
      ...monacoRef.current.languages.typescript.typescriptDefaults
        .getCompilerOptions(),
      allowJs: true,
      esModuleInterop: true,
      experimentalDecorators: true,
      inlineSourceMap: true,
      isolatedModules: true,
      jsx: monacoRef.current.languages.typescript.JsxEmit.React,
      lib: ["deno.window"],
      module: monacoRef.current.languages.typescript.ModuleKind.ESNext,
      strict: true,
      target: monacoRef.current.languages.typescript.ScriptTarget.ESNext,
      useDefineForClassFields: true,
    };

    const extraLib: {
      content: string;
      filePath?: string;
    } = {
      content: lib.current,
      filePath: "lib.deno.d.ts",
    };

    monacoRef.current.languages.typescript.typescriptDefaults
      .setCompilerOptions(compilerOptions);
    monacoRef.current.languages.typescript.javascriptDefaults
      .setCompilerOptions(compilerOptions);

    monacoRef.current.languages.typescript.typescriptDefaults.addExtraLib(
      extraLib.content,
      extraLib.filePath,
    );
    monacoRef.current.languages.typescript.javascriptDefaults.addExtraLib(
      extraLib.content,
      extraLib.filePath,
    );
  };

  useMount(() => {
    fetch(asset("lib.deno.d.ts"))
      .then((res) => res.text())
      .then((text) => {
        lib.current = text;
        if (monacoRef.current) loadLib();
      });
  });

  return (
    <Editor
      defaultLanguage="typescript"
      {...props}
      beforeMount={handleBeforeMount}
    />
  );
};

export default memo(DenoEditor);
